Repository Auto-Review/ori-front, pull requests merged in 2025-07, with the labels that each got.

#35 [PR]: 멱등성 문제 해결
  src/pages/MyPage.js
Labels: bugfix

#34 [Release] 백엔드 기능 추가에 맞는 디자인 변경
  src/App.js
  src/auth/axiosInstance.js
  src/pages/BookmarkTILPage.js
  src/pages/CodeDetailsPage.js
  src/pages/CodeListPage.js
  src/pages/CodeSavePage.js
  src/pages/CodeUpdatePage.js
  src/pages/GithubCallback.js
  src/pages/HomePage.js
  src/pages/LoginPage.js
  src/pages/MyCodeListPage.js
  src/pages/MyPage.js
  src/pages/MyTILListPage.js
  src/pages/Navbar.js
  src/pages/TILDetailsPage.js
  src/pages/TILListPage.js
Labels: release

#36 [Refactor] github 연동 리다이렉트 주소 변경
  src/pages/MyPage.js
Labels: refactor
